/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao;

import br.com.controle.Votacao;
import javax.swing.JOptionPane;

/**
 *
 * @author luiza
 */
public class Tela extends javax.swing.JFrame {
    Votacao v =new Votacao ();
    

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTmatricula = new javax.swing.JTextField();
        jRcontador1 = new javax.swing.JRadioButton();
        jRcontador2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLcontador1 = new javax.swing.JLabel();
        jLcontador2 = new javax.swing.JLabel();
        jLcontadorVotos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBresultadoFinal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite sua matricula:");

        buttonGroup1.add(jRcontador1);
        jRcontador1.setText("40 horas");
        jRcontador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRcontador1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRcontador2);
        jRcontador2.setText("44 horas");
        jRcontador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRcontador2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Vote ");

        jLcontador1.setText("0");

        jLcontador2.setText("0");

        jLcontadorVotos.setText("0");

        jLabel3.setText("Aperte para ver o resultado final:");

        jBresultadoFinal.setBackground(new java.awt.Color(51, 0, 0));
        jBresultadoFinal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBresultadoFinal.setForeground(new java.awt.Color(255, 255, 255));
        jBresultadoFinal.setText("exit");
        jBresultadoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBresultadoFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTmatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jRcontador1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLcontador1, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                                    .addComponent(jLcontador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLcontadorVotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jLabel2)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRcontador2)
                            .addComponent(jBresultadoFinal))))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRcontador1)
                    .addComponent(jRcontador2))
                .addGap(38, 38, 38)
                .addComponent(jLcontador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLcontador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLcontadorVotos)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jBresultadoFinal))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRcontador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRcontador1ActionPerformed
        // TODO add your handling code here:
        if(jTmatricula.getText().equals("")){
        JOptionPane.showMessageDialog(rootPane, "Campo Obrigatorio!");
        jTmatricula.requestFocus();
        }else{
        
        if(jRcontador1.isSelected()){
        v.contador1++;
        } 
        v.setMatricula(Integer.valueOf(jTmatricula.getText()));
        jLcontador1.setText("Votos para 40h: "+v.votos40h());
        jLcontadorVotos.setText("Pessoas que votaram:"+v.contador());
        
            }
        
    }//GEN-LAST:event_jRcontador1ActionPerformed

    private void jRcontador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRcontador2ActionPerformed
        // TODO add your handling code here:
        if(jRcontador2.isSelected()){
        v.contador2++;
        }
        v.setMatricula(Integer.valueOf(jTmatricula.getText()));
        jLcontador2.setText("Votos para 44h: "+v.votos44h());
        jLcontadorVotos.setText("Pessoas que votaram:"+v.contador());
            
    }//GEN-LAST:event_jRcontador2ActionPerformed

    private void jBresultadoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBresultadoFinalActionPerformed
        // TODO add your handling code here:    
        if (v.contador1 > v.contador2) {
        JOptionPane.showMessageDialog(null, "Candidato 1 recebeu mais votos.");
         } else if (v.contador2 > v.contador1) {
        JOptionPane.showMessageDialog(null, "Candidato 2 recebeu mais votos.");
        } else {
         JOptionPane.showMessageDialog(null, "Os candidatos receberam a mesma quantidade de votos.");
        }
        
    }//GEN-LAST:event_jBresultadoFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBresultadoFinal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLcontador1;
    private javax.swing.JLabel jLcontador2;
    private javax.swing.JLabel jLcontadorVotos;
    private javax.swing.JRadioButton jRcontador1;
    private javax.swing.JRadioButton jRcontador2;
    private javax.swing.JTextField jTmatricula;
    // End of variables declaration//GEN-END:variables
}
