/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import controle.Voto44h;
import controle.Votos40h;
import javax.swing.JOptionPane;


public class Tela extends javax.swing.JFrame {
Votos40h c1 = new Votos40h();
Voto44h c2 = new Voto44h();
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jTmatricula = new javax.swing.JTextField();
        jR40h = new javax.swing.JRadioButton();
        jR44h = new javax.swing.JRadioButton();
        jLcontador1 = new javax.swing.JLabel();
        jLcontador2 = new javax.swing.JLabel();
        jLcontadorVotos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Digite sua matricula:");

        jTmatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTmatriculaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jR40h);
        jR40h.setText("40h");
        jR40h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR40hActionPerformed(evt);
            }
        });

        buttonGroup1.add(jR44h);
        jR44h.setText("44h");
        jR44h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR44hActionPerformed(evt);
            }
        });

        jLcontador1.setText("0");

        jLcontador2.setText("0");

        jLcontadorVotos.setText("0");

        jButton1.setText("Resultado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLcontadorVotos)
                    .addComponent(jLcontador2)
                    .addComponent(jLcontador1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jR40h)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jR44h))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jTmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jR40h)
                    .addComponent(jR44h))
                .addGap(37, 37, 37)
                .addComponent(jLcontador1)
                .addGap(18, 18, 18)
                .addComponent(jLcontador2)
                .addGap(18, 18, 18)
                .addComponent(jLcontadorVotos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel3))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTmatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTmatriculaActionPerformed

    private void jR44hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR44hActionPerformed
        // TODO add your handling code here:
     if(jTmatricula.getText().equals("")){
        JOptionPane.showMessageDialog(rootPane, "Campo Obrigatorio!");
        jTmatricula.requestFocus();
        }else{
        if(jR44h.isSelected()){
        } }
        c1.setMatricula(Integer.valueOf(jTmatricula.getText()));
        jLcontador2.setText("Votos para 44h: "+c2.Votar(WIDTH));
        jLcontadorVotos.setText("Pessoas que votaram:"+c1.contador());
        
            
       
    }//GEN-LAST:event_jR44hActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if (c1.Votar(WIDTH) > c2.Votar(WIDTH)) {
        JOptionPane.showMessageDialog(null, "Candidato 1 recebeu mais votos.");
         } else if (c1.Votar(WIDTH) < c2.Votar(WIDTH)) {
        JOptionPane.showMessageDialog(null, "Candidato 2 recebeu mais votos.");
        } else {
         JOptionPane.showMessageDialog(null, "Os candidatos receberam a mesma quantidade de votos.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jR40hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR40hActionPerformed
        // TODO add your handling code here:
        
         if(jTmatricula.getText().equals("")){
        JOptionPane.showMessageDialog(rootPane, "Campo Obrigatorio!");
        jTmatricula.requestFocus();
        }else{
        
        if(jR40h.isSelected()){
      
        } 
        c1.setMatricula(Integer.valueOf(jTmatricula.getText()));
        jLcontador1.setText("Votos para 40h: "+c1.Votar(WIDTH));
        jLcontadorVotos.setText("Pessoas que votaram:"+c1.contador());
        
            }
    }//GEN-LAST:event_jR40hActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLcontador1;
    private javax.swing.JLabel jLcontador2;
    private javax.swing.JLabel jLcontadorVotos;
    private javax.swing.JRadioButton jR40h;
    private javax.swing.JRadioButton jR44h;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTmatricula;
    // End of variables declaration//GEN-END:variables
}
